### PR TITLE
Preserve puzzle contents (entities) when changing width and height #22

### PR DESCRIPTION
**Pull request by ianh**
Add a new `setSize` method to Grid that copies over elements from the
old grid.

Now that changing the grid size doesn't clear the puzzle, add an "erase
all button" to do that.  Pipe the erase all method through from the UI
to the grid.

### CODE REVIEW

**Comment by ianh** [comment]
BTW, I was a bit confused by all the different "Grid" objects.  There's `Grid`, `GridService`, `GridRenderer`, `GridUi`, and `GridUiHook`.  From my (naive) perspective, it seems like there ought to be only two: one to represent the grid data (`Grid` seems to do this nicely) and one to handle displaying and interacting with the grid.

**Comment by ianh** [comment]
Also, fixes #22 (dunno why it doesn't link from the commit title).

**Comment by gracenotes** [comment]
Ah yeah, I think a diagram of Grid stuff might help. To write it out here:
- Grid is the low-level data structure for puzzles
- GridRenderer renders a Grid, and is used by the (non-interactive) front page and by puzzles
- GridUi renders a Grid through GridRenderer and adds interaction to it, used by puzzles and editor
- GridService caches and stores Grids received from server, managing async fetching of data and lazy initialization of Grid etc from data
- GridUiHook is a hacky way to callback into the Angular app from GridUi

As you may have guessed, originally everything outside the Angular app was in one big Grid class, and it had about 20 cleanly partitionable fields, where >half went unused in some situations.

**Comment by ianh** [comment]
Ah, that makes sense, thanks!

**Pull request merged**
